### ISSUE TITLE
Allow encoded body of requests

### ISSUE THREAD

**Issue by CDaRip2U** [sassoftware/unravl#95]
We should have a way to encode the "body" of a submission in some way that does not require us to escape other media types within the body of a UNRAVL submission.   Example: SAS Code within the string needs to be extra careful of escaping " or ' values or the JSON of UNRAVL is invalid?   

I did not see this covered in https://github.com/sassoftware/unravl/blob/master/doc/Body.md.  It does mention BINARY, but i think this is more ability to specify encoding "BASE64" for example and body value, and have it "unwrapped" before submission.

**Comment by DavidBiesack** [comment]
The `"body"` can refer to an external file/resource instead of embedding it it the JSON UnRAVL script and encoding it as JSON - use 
```
"body" : { "text" : "@source/prog1.sas" }
```
for example. The `@` character is a special character which indicates the source is in a file (or a web resource if you use `"@http://www.example.com/some/resource.txt"`)

We can't change any encoding for the UnRAVL script, as it must be fully conforming JSON.   However, note that single quote characters `'` do not need any escaping in a JSON string, and SAS programs can accept string literals which are enclosed in single quotes.:
```
  s = 'this is a string';
```

If these options still do not give you what you want, please create a more specific use case or proposal. i.e. using an option on the `"text"` element such as `"replace" : { "'", "\"" }` which would perform string replacements in the input before sending it.
